### ISSUE TITLE
Bug: Sensor can no longer be created

### ISSUE THREAD

**Issue by domeq** [snicker/zwift_hass#42] opened 2023-09-16 13:15 UTC
Hi!
This is yet another report of https://github.com/snicker/zwift_hass/issues/39 and https://github.com/snicker/zwift_hass/issues/37.
I have v3.3.1 installed, I'm running Home Assistant 2023.9.1 as docker image. Sadly the sensors are still unavailable.

This is the error I'm getting when HA is starting:
```
homeassistant  | 2023-09-10 20:51:07.069 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration zwift which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
homeassistant  | 2023-09-10 20:51:24.695 ERROR (MainThread) [custom_components.zwift.sensor] Could not create Zwift sensor named 'Zwift'!
homeassistant  |   File "/config/custom_components/zwift/sensor.py", line 124, in async_setup_platform
homeassistant  |     await zwift_data._connect()
homeassistant  |   File "/config/custom_components/zwift/sensor.py", line 343, in _connect
homeassistant  |     from zwift import Client as ZwiftClient
homeassistant  |   File "/usr/local/lib/python3.11/site-packages/zwift/__init__.py", line 4, in <module>
homeassistant  |   File "/usr/local/lib/python3.11/site-packages/zwift/client.py", line 5, in <module>
homeassistant  |   File "/usr/local/lib/python3.11/site-packages/zwift/world.py", line 2, in <module>
homeassistant  |     from . import zwift_messages_pb2
homeassistant  |   File "/usr/local/lib/python3.11/site-packages/zwift/zwift_messages_pb2.py", line 35, in <module>
```

The extension has been broken for a few months, nothing changed for me after you released v3.3.1.
I tried removing the extension and configuration related to it and reinstalling - no improvement.
Any tips what can I do to fix it?

**Comment by snicker** [comment] 2023-09-17 02:35
Closing as duplicate of #37 and re-opening that issue. Please direct discussion there.

**Closed by snicker** 2023-09-17 02:35 UTC
Labels: duplicate
